### ISSUE TITLE
auto-commit v0.1.5 fails with 'Couldn't complete prompt' error on macOS

### ISSUE THREAD

**Issue by kieranklaassen** [m1guelpf/auto-commit#22]
**Summary:**  
Auto Commit 0.1.5 encounters a runtime error when analyzing a codebase on macOS (Darwin-aarch64). The error message suggests that the required model 'code-davinci-002' does not exist.

**Installed version:**  
Auto Commit 0.1.5 (Darwin-aarch64)

**Installation method:**  
Installed using the following command:
```bash
curl -fsSL https://raw.githubusercontent.com/m1guelpf/auto-commit/main/install.sh | sh -
```

**Error Message**
```
Loading Data...
▐   ⠈    ▌ Analyzing Codebase...thread 'main' panicked at 'Couldn't complete prompt.: Api(ErrorMessage { message: "The model: `code-davinci-002` does not exist", error_type: "invalid_request_error" })', src/main.rs:137:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
▐    ⠂   ▌ Analyzing Codebase...
```

## Steps to reproduce:

- Install Auto Commit 0.1.5 on macOS (Darwin-aarch64) using the provided installation command.
- Run auto-commit in a terminal.
- Observe the error message displayed during the "Analyzing Codebase" step.

### Expected behavior:
Auto Commit should analyze the codebase without encountering any errors.

### Actual behavior:
Auto Commit fails with a 'Couldn't complete prompt' error related to a missing model 'code-davinci-002'.

**Comment by m1guelpf** [comment]
Should be fixed in the latest release! 😄
